config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  resources :reminders
  resources :books
  get 'manifest.json' => 'metadata#manifest', as: :manifest
  post '/push', to: 'reminders#notification'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reminders
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates_presence_of :name
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  belongs_to :book
  validates_presence_of :book, :date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  @decodedVapidPublicKey = Base64.urlsafe_decode64('BEMZ2BN-VwYbvzGIsKSeqdWjxnnZ6OFxZNBqCQtJX0gXV005SzIZoJ9EIHwBDe1x8h9LU9_HlAMKquW8EWvDycg=').bytes
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html {redirect_to @book, notice: 'Book was successfully created.'}
        format.json {render :show, status: :created, location: @book}
      else
        format.html {render :new}
        format.json {render json: @book.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html {redirect_to @book, notice: 'Book was successfully updated.'}
        format.json {render :show, status: :ok, location: @book}
      else
        format.html {render :edit}
        format.json {render json: @book.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.avatar = nil
    @book.destroy
    respond_to do |format|
      format.html {redirect_to books_url, notice: 'Book was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:name, :pages, :avatar)
  end
end

app/controllers/metadata_controller.rb
class MetadataController < ApplicationController
  layout false

  def manifest
    manifest = {
        name: 'Books Time',
        short_name: 'BkTime',
        display: 'standalone',
        start_url:'/',
        orientation: 'portrait',
        icons:[
            {
                src: 'images/logo.png',
                sizes: '144x144',
                type: 'image/png'
            }
        ],
        gm_sender_id:  'xxxxxx'
    }

    render json: manifest.to_json
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]

  # GET /reminders
  # GET /reminders.json
  def index
    @reminders = Reminder.all
  end

  # GET /reminders/1
  # GET /reminders/1.json
  def show
  end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  def edit
  end

  # POST /reminders
  # POST /reminders.json
  def create
    @reminder = Reminder.new(reminder_params)

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1
  # PATCH/PUT /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1
  # DELETE /reminders/1.json
  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def notification
    Webpush.payload_send(
        message: params[:message],
        endpoint: params[:subscription][:endpoint],
        p256dh: params[:subscription][:keys][:p256dh],
        auth: params[:subscription][:keys][:auth],
        ttl: 24 * 60 * 60,
        vapid: {
        subject: 'mailto:sender@example.com',
        public_key: ENV['BEMZ2BN-VwYbvzGIsKSeqdWjxnnZ6OFxZNBqCQtJX0gXV005SzIZoJ9EIHwBDe1x8h9LU9_HlAMKquW8EWvDycg='],
        private_key: ENV['CAuuykuxL7k5V2Y8U_p_P2U_ghE9gaEnVEBWizE3Ixw=']
    }
    )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reminder_params
      params.require(:reminder).permit(:date,:book_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
  def date_format(date)
    date.strftime('%d/%m/%Y - %H:%M')
  end
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true, html:{:role=>'form'}) do |form| %>
    <div class="box-body">
      <% if book.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

            <ul>
              <% book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= form.label 'Nome', for: :book_name %>
        <%= form.text_field :name, id: :book_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label 'Paginas',for: :book_pages %>
        <%= form.number_field :pages, id: :book_pages, class: 'form-control'%>
      </div>
      <div class="form-group">
        <%= form.label 'Foto' %>
        <%= form.file_field :avatar, class: 'form-control' %>
      </div>

    </div>
    <div class="box-footer">
      <%= form.submit 'Salvar', type:'submit', class:'btn btn-primary'%>
      <%= link_to 'Cancelar', books_path, class:'btn btn-danger' %>
    </div>
<% end %>

app/views/books/edit.html.erb
<section class="content-header">
  <h1>Livros</h1>
</section>
<section class="content">
  <div class="box box-primary">
    <div class="box-header whit-border">
      <h3 class="box-title">Editar Livro</h3>
    </div>
    <%= render 'form', book: @book %>
  </div>
</section>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<section class="content-header">
  <h1>Livro</h1>
</section>
<section class="content">
  <div class="col-md-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Listagem de
          livros</h3> <%= link_to 'Novo Livro', new_book_path, class: 'btn btn-primary  pull-right' %>
      </div>
      <div class="box-body no-padding">
        <table class="table table-striped">
          <tr>
            <th colspan="2">Nome</th>
            <th>Paginas</th>
            <th>Ações</th>
          </tr>
          <% @books.each do |book| %>
              <tr>
                <td colspan="2"><%= image_tag book.avatar.url(:thumb) %> <%= book.name %></td>
                <td><%= book.pages %></td>
                <td><a href="books/<%= book.id %>" class="btn btn-primary btn-xs"><i class="fa fa-bars"></i></a>
                  <a href="<%= edit_book_path(book) %>" class="btn btn-warning btn-xs"><i class="fa fa-pencil"></i></a>
                  <a href="books/<%= book.id %>" class='btn btn-danger btn-xs' data-method="delete" data-confirm="Tem Certeza?"><i class="fa fa-trash-o"></i></a>
                </td>
              </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/books/new.html.erb
<section class="content-header">
  <h1>Livros</h1>
</section>
<section class="content">
    <div class="box box-primary">
      <div class="box-header whit-border">
        <h3 class="box-title">Novo Livro</h3>
      </div>
      <%= render 'form', book: @book %>
    </div>
</section>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Pages:</strong>
  <%= @book.pages %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Book's Time</title>
  <%= csrf_meta_tags %>
  <link rel="manifest" href="/manifest.json">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'bootstrap/bootstrap.min.css',
                          'font-awesome/css/font-awesome.min',
                          'Ionicons/css/ionicons.min',
                          'admin/AdminLTE.min',
                          'admin/skins/skin-blue',
                          'datepicker/bootstrap-datepicker.min'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'jquery.slimscroll.min',
                             'bootstrap.min',
                             'fastclick',
                             'pages/dashboard2',
                             'datepicker/js/bootstrap-datepicker.min',
                             'adminlte.min',
                             'demo'
  %>

</head>

<body class="skin-blue sidebar-mini">
<script>
    window.vapidPublicKey = new Uint8Array(<%= @decodedVapidPublicKey %>);
</script>
<div class="wrapper">
  <header class="main-header">
    <a href="" class="logo"></a>
    <nav class="navbar navbar-static-top">
      <a href="" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown notifications-menu">
            <a href="" class="dropdown-toogle" data-toggle="dropdown" aria-expanded = "false">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning">10</span>
            </a>
          </li>
          <li class="dropdown notifications-menu">
            <a href="" class="dropdown-toogle" data-toggle="dropdown" aria-expanded = "false">
              <i class="fa fa-flag-o"></i>
              <span class="label label-warning">10</span>
            </a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <aside class="main-sidebar">
    <section class="sidebar">
      <ul class="sidebar-menu tree" data-widget="tree">
        <li class="header">MENU DE NAVEGAÇÃO</li>
        <li><a href="<%=books_path%>"><span>Livros</span></a></li>
        <li><a href="<%=reminders_path%>"><span>Lembretes</span></a></li>
      </ul>
    </section>
  </aside>
  <div class="content-wrapper">
    <%= yield %>
  </div>
  <footer class="main-footer"></footer>
  <aside class="control-sidebar control-sidebar-dark"></aside>
  <div class="control-sidebar-bg"></div>
</div>
</body>
</html>

app/views/reminders/_form.html.erb
<%= form_with(model: reminder, local: true, html: {:role => 'form'}) do |form| %>
    <div class="box-body">
      <% if reminder.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

            <ul>
              <% reminder.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= form.label 'Data' %>
        <div class="input-group date">
          <div class="input-group-addon"><i class="fa fa-clock-o"></i></div>
          <%= form.datetime_select :date, class: 'form-control pull-right', id: 'datepicker' %>
        </div>
      </div>

      <div class="form-group">
        <%= form.label 'Livro', for: :book_pages %>
        <%= collection_select(:reminder, :book_id, Book.all, :id, :name,{prompt:true},class:'form-control')%>
      </div>
    </div>
    <div class="box-footer">
      <%= form.submit 'Salvar', type: 'submit', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/reminders/edit.html.erb
<section class="content-header">
  <h1>Lembretes</h1>
</section>
<section class="content">
  <div class="box box-primary">
    <div class="box-header whit-border">
      <h3 class="box-title">Editar Lembrete</h3>
    </div>
    <%= render 'form', reminder: @reminder %>
  </div>
</section>

app/views/reminders/index.html.erb
<p id="notice"><%= notice %></p>
<section class="content-header">
  <h1>Lembretes</h1>
</section>
<section class="content">
  <div class="col-md-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Listagem de
          lembretes</h3> <%= link_to 'Novo Lembrete', new_reminder_path, class: 'btn btn-primary  pull-right' %>
      </div>
      <div class="box-body no-padding">
        <table class="table table-striped">
          <tr>
            <th>Livro</th>
            <th>Data</th>
            <th>Ações</th>
          </tr>
          <% @reminders.each do |reminder| %>
              <tr>
                <td><%= reminder.book.name%></td>
                <td><%= date_format reminder.date %></td>
                <td><a href="books/<%= reminder.id %>" class="btn btn-primary btn-xs"><i class="fa fa-bars"></i></a>
                  <a href="<%= edit_reminder_path(reminder) %>" class="btn btn-warning btn-xs"><i class="fa fa-pencil"></i></a>
                  <a href="reminders/<%= reminder.id %>" class='btn btn-danger btn-xs' data-method="delete" data-confirm="Tem Certeza?"><i class="fa fa-trash-o"></i></a>
                </td>
              </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/reminders/new.html.erb
<section class="content-header">
  <h1>Lembretes</h1>
</section>
<section class="content">
  <div class="box box-primary">
    <div class="box-header whit-border">
      <h3 class="box-title">Novo Lembrete</h3>
    </div>
    <%= render 'form', reminder: @reminder %>
  </div>
</section>

app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @reminder.date %>
</p>

<%= link_to 'Edit', edit_reminder_path(@reminder) %> |
<%= link_to 'Back', reminders_path %>